// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chord.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChordMessage_Command int32

const (
	ChordMessage_Ping       ChordMessage_Command = 1
	ChordMessage_Pong       ChordMessage_Command = 2
	ChordMessage_GetPred    ChordMessage_Command = 3
	ChordMessage_GetId      ChordMessage_Command = 4
	ChordMessage_GetFingers ChordMessage_Command = 5
	ChordMessage_ClaimPred  ChordMessage_Command = 6
	ChordMessage_GetSucc    ChordMessage_Command = 7
)

var ChordMessage_Command_name = map[int32]string{
	1: "Ping",
	2: "Pong",
	3: "GetPred",
	4: "GetId",
	5: "GetFingers",
	6: "ClaimPred",
	7: "GetSucc",
}

var ChordMessage_Command_value = map[string]int32{
	"Ping":       1,
	"Pong":       2,
	"GetPred":    3,
	"GetId":      4,
	"GetFingers": 5,
	"ClaimPred":  6,
	"GetSucc":    7,
}

func (x ChordMessage_Command) Enum() *ChordMessage_Command {
	p := new(ChordMessage_Command)
	*p = x
	return p
}

func (x ChordMessage_Command) String() string {
	return proto.EnumName(ChordMessage_Command_name, int32(x))
}

func (x *ChordMessage_Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChordMessage_Command_value, data, "ChordMessage_Command")
	if err != nil {
		return err
	}
	*x = ChordMessage_Command(value)
	return nil
}

func (ChordMessage_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{4, 0}
}

type SendIdMessage struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendIdMessage) Reset()         { *m = SendIdMessage{} }
func (m *SendIdMessage) String() string { return proto.CompactTextString(m) }
func (*SendIdMessage) ProtoMessage()    {}
func (*SendIdMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{0}
}

func (m *SendIdMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendIdMessage.Unmarshal(m, b)
}
func (m *SendIdMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendIdMessage.Marshal(b, m, deterministic)
}
func (m *SendIdMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendIdMessage.Merge(m, src)
}
func (m *SendIdMessage) XXX_Size() int {
	return xxx_messageInfo_SendIdMessage.Size(m)
}
func (m *SendIdMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendIdMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendIdMessage proto.InternalMessageInfo

func (m *SendIdMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type FingerMessage struct {
	Address              *string  `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Id                   *string  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FingerMessage) Reset()         { *m = FingerMessage{} }
func (m *FingerMessage) String() string { return proto.CompactTextString(m) }
func (*FingerMessage) ProtoMessage()    {}
func (*FingerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{1}
}

func (m *FingerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerMessage.Unmarshal(m, b)
}
func (m *FingerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerMessage.Marshal(b, m, deterministic)
}
func (m *FingerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerMessage.Merge(m, src)
}
func (m *FingerMessage) XXX_Size() int {
	return xxx_messageInfo_FingerMessage.Size(m)
}
func (m *FingerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FingerMessage proto.InternalMessageInfo

func (m *FingerMessage) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *FingerMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type PredMessage struct {
	Pred                 *FingerMessage `protobuf:"bytes,1,req,name=pred" json:"pred,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PredMessage) Reset()         { *m = PredMessage{} }
func (m *PredMessage) String() string { return proto.CompactTextString(m) }
func (*PredMessage) ProtoMessage()    {}
func (*PredMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{2}
}

func (m *PredMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredMessage.Unmarshal(m, b)
}
func (m *PredMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredMessage.Marshal(b, m, deterministic)
}
func (m *PredMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredMessage.Merge(m, src)
}
func (m *PredMessage) XXX_Size() int {
	return xxx_messageInfo_PredMessage.Size(m)
}
func (m *PredMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PredMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PredMessage proto.InternalMessageInfo

func (m *PredMessage) GetPred() *FingerMessage {
	if m != nil {
		return m.Pred
	}
	return nil
}

type SendFingersMessage struct {
	Fingers              []*FingerMessage `protobuf:"bytes,1,rep,name=fingers" json:"fingers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendFingersMessage) Reset()         { *m = SendFingersMessage{} }
func (m *SendFingersMessage) String() string { return proto.CompactTextString(m) }
func (*SendFingersMessage) ProtoMessage()    {}
func (*SendFingersMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{3}
}

func (m *SendFingersMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFingersMessage.Unmarshal(m, b)
}
func (m *SendFingersMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFingersMessage.Marshal(b, m, deterministic)
}
func (m *SendFingersMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFingersMessage.Merge(m, src)
}
func (m *SendFingersMessage) XXX_Size() int {
	return xxx_messageInfo_SendFingersMessage.Size(m)
}
func (m *SendFingersMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFingersMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendFingersMessage proto.InternalMessageInfo

func (m *SendFingersMessage) GetFingers() []*FingerMessage {
	if m != nil {
		return m.Fingers
	}
	return nil
}

type ChordMessage struct {
	Cmd                  *ChordMessage_Command `protobuf:"varint,1,req,name=cmd,enum=chord.internal.ChordMessage_Command" json:"cmd,omitempty"`
	Cpmsg                *PredMessage          `protobuf:"bytes,2,opt,name=cpmsg" json:"cpmsg,omitempty"`
	Sidmsg               *SendIdMessage        `protobuf:"bytes,4,opt,name=sidmsg" json:"sidmsg,omitempty"`
	Sfmsg                *SendFingersMessage   `protobuf:"bytes,5,opt,name=sfmsg" json:"sfmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ChordMessage) Reset()         { *m = ChordMessage{} }
func (m *ChordMessage) String() string { return proto.CompactTextString(m) }
func (*ChordMessage) ProtoMessage()    {}
func (*ChordMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{4}
}

func (m *ChordMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChordMessage.Unmarshal(m, b)
}
func (m *ChordMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChordMessage.Marshal(b, m, deterministic)
}
func (m *ChordMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChordMessage.Merge(m, src)
}
func (m *ChordMessage) XXX_Size() int {
	return xxx_messageInfo_ChordMessage.Size(m)
}
func (m *ChordMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChordMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChordMessage proto.InternalMessageInfo

func (m *ChordMessage) GetCmd() ChordMessage_Command {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ChordMessage_Ping
}

func (m *ChordMessage) GetCpmsg() *PredMessage {
	if m != nil {
		return m.Cpmsg
	}
	return nil
}

func (m *ChordMessage) GetSidmsg() *SendIdMessage {
	if m != nil {
		return m.Sidmsg
	}
	return nil
}

func (m *ChordMessage) GetSfmsg() *SendFingersMessage {
	if m != nil {
		return m.Sfmsg
	}
	return nil
}

type NetworkMessage struct {
	Proto                *uint32  `protobuf:"varint,1,req,name=proto" json:"proto,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkMessage) Reset()         { *m = NetworkMessage{} }
func (m *NetworkMessage) String() string { return proto.CompactTextString(m) }
func (*NetworkMessage) ProtoMessage()    {}
func (*NetworkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{5}
}

func (m *NetworkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMessage.Unmarshal(m, b)
}
func (m *NetworkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMessage.Marshal(b, m, deterministic)
}
func (m *NetworkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMessage.Merge(m, src)
}
func (m *NetworkMessage) XXX_Size() int {
	return xxx_messageInfo_NetworkMessage.Size(m)
}
func (m *NetworkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMessage proto.InternalMessageInfo

func (m *NetworkMessage) GetProto() uint32 {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return 0
}

func (m *NetworkMessage) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("chord.internal.ChordMessage_Command", ChordMessage_Command_name, ChordMessage_Command_value)
	proto.RegisterType((*SendIdMessage)(nil), "chord.internal.SendIdMessage")
	proto.RegisterType((*FingerMessage)(nil), "chord.internal.FingerMessage")
	proto.RegisterType((*PredMessage)(nil), "chord.internal.PredMessage")
	proto.RegisterType((*SendFingersMessage)(nil), "chord.internal.SendFingersMessage")
	proto.RegisterType((*ChordMessage)(nil), "chord.internal.ChordMessage")
	proto.RegisterType((*NetworkMessage)(nil), "chord.internal.NetworkMessage")
}

func init() {
	proto.RegisterFile("chord.proto", fileDescriptor_541dae51990542ec)
}

var fileDescriptor_541dae51990542ec = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x6b, 0xab, 0x40,
	0x14, 0x86, 0xf1, 0x2b, 0xc6, 0xe3, 0x55, 0x64, 0xb8, 0x0b, 0xe1, 0x72, 0x69, 0x90, 0x2e, 0xb2,
	0x12, 0x12, 0x68, 0x9b, 0xee, 0x4a, 0x03, 0x0d, 0x59, 0xa4, 0x84, 0xc9, 0xae, 0x3b, 0x71, 0x26,
	0x56, 0x1a, 0xc7, 0x30, 0x63, 0xe9, 0xaf, 0xec, 0x7f, 0x2a, 0x33, 0xe3, 0x84, 0x98, 0x16, 0xba,
	0x9b, 0x93, 0x3c, 0xcf, 0xeb, 0x3b, 0x47, 0x21, 0x2c, 0x5f, 0x5b, 0x4e, 0xf2, 0x23, 0x6f, 0xbb,
	0x16, 0xc5, 0x7a, 0xa8, 0x59, 0x47, 0x39, 0x2b, 0x0e, 0xd9, 0x15, 0x44, 0x3b, 0xca, 0xc8, 0x9a,
	0x6c, 0xa8, 0x10, 0x45, 0x45, 0x51, 0x0c, 0x76, 0x4d, 0x52, 0x6b, 0x62, 0x4f, 0x03, 0x6c, 0xd7,
	0x24, 0xbb, 0x87, 0xe8, 0xa9, 0x66, 0x15, 0xe5, 0x06, 0x48, 0xc1, 0x2f, 0x08, 0xe1, 0x54, 0x88,
	0x9e, 0x32, 0x63, 0xaf, 0xda, 0x27, 0xf5, 0x01, 0xc2, 0x2d, 0xa7, 0xa7, 0xe4, 0x19, 0xb8, 0x47,
	0x4e, 0x75, 0x76, 0x38, 0xff, 0x9f, 0x0f, 0x9b, 0xe4, 0x83, 0xa7, 0x60, 0x85, 0x66, 0x1b, 0x40,
	0xb2, 0x9d, 0xfe, 0x4b, 0x98, 0xa0, 0x3b, 0xf0, 0xf7, 0xfa, 0x97, 0xd4, 0x9a, 0x38, 0xbf, 0x67,
	0x19, 0x3a, 0xfb, 0xb4, 0xe1, 0xcf, 0x52, 0x92, 0x26, 0xe9, 0x16, 0x9c, 0xb2, 0xd1, 0x8d, 0xe2,
	0xf9, 0xf5, 0x65, 0xca, 0x39, 0x9a, 0x2f, 0xdb, 0xa6, 0x29, 0x18, 0xc1, 0x52, 0x40, 0x33, 0xf0,
	0xca, 0x63, 0x23, 0xaa, 0xd4, 0x9e, 0x58, 0xd3, 0x70, 0xfe, 0xef, 0xd2, 0x3c, 0xbb, 0x36, 0xd6,
	0x24, 0xba, 0x81, 0x91, 0xa8, 0x89, 0x74, 0x5c, 0xe5, 0x7c, 0xeb, 0x3c, 0x78, 0x0d, 0xb8, 0x87,
	0xd1, 0x02, 0x3c, 0xb1, 0x97, 0x96, 0xa7, 0xac, 0xec, 0x27, 0x6b, 0xb8, 0x1e, 0xac, 0x85, 0xac,
	0x00, 0xbf, 0xef, 0x8c, 0xc6, 0xe0, 0x6e, 0x6b, 0x56, 0x25, 0x96, 0x3a, 0xb5, 0xac, 0x4a, 0x6c,
	0x14, 0x82, 0xbf, 0xa2, 0x9d, 0x2c, 0x9a, 0x38, 0x28, 0x00, 0x6f, 0x45, 0xbb, 0x35, 0x49, 0x5c,
	0x14, 0x03, 0xac, 0x68, 0xd7, 0x47, 0x26, 0x1e, 0x8a, 0x20, 0x58, 0x1e, 0x8a, 0xba, 0x51, 0xe4,
	0xa8, 0xd7, 0x76, 0xef, 0x65, 0x99, 0xf8, 0xd9, 0x02, 0xe2, 0x67, 0xda, 0x7d, 0xb4, 0xfc, 0xcd,
	0x2c, 0xf4, 0x2f, 0x78, 0xea, 0x3b, 0x53, 0x2b, 0x8d, 0xb0, 0x1e, 0x50, 0x02, 0x8e, 0x59, 0x56,
	0x80, 0xe5, 0xf1, 0x11, 0x5e, 0xc6, 0xe6, 0x0a, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x14,
	0x6e, 0xd4, 0xa0, 0x02, 0x00, 0x00,
}
